### PR TITLE
Draft Process Chapter

### PR DESCRIPTION
**Pull request by xmatthewx**
Hey team. Don't merge. Add you comments in the pull request. I will edit. Then we can merge.

### CODE REVIEW

**Comment by xmatthewx** [comment]
You can add a comment inline via the `files changed` tab above. 

screenshot 2015-02-02 12 53 18


Click the plus sign by the line number. 

screenshot 2015-02-02 12 51 45

**Comment by xmatthewx** [comment]
You can read an [easier-on-the-eyes](https://github.com/xmatthewx/Mofo-Design-Handbook/tree/master/Process) version in my repo.

**Comment by xmatthewx** [comment]
cc @iamjessklein @flukeout @vazquez @sabrinang

**Comment by xmatthewx** [comment]
@cassiemc

**Comment by xmatthewx** [comment]
this is for issue #8

**Comment by cassiemc** [comment]
@xmatthewx just saw this from ages ago. Should I merge this?

**Comment by xmatthewx** [comment]
This content now lives in the wiki https://github.com/MozillaFoundation/Design/wiki/Process-(super-fun.-seriously.)

**Pull request closed without merging**
