### PR TITLE
Create brand update checklist for design team

### PR DESCRIPTION
**Pull request by natalieworth**
The MoFo Design team is creating a ticket template checklist (based on Mavis' design to dev handoff), for updating, changing, or adding new styles to our brand documentation.

### CODE REVIEW

**Comment by natalieworth** [comment]
@alanmoo @xmatthewx  I added this to the design repo (instead of foundation.mozilla). Made a pull request (and got guidance from @mmmavis) but let me know if there are any issues/ changes with this tic. Thanks.

**Comment by alanmoo** [comment]
This is fine, though you can also commit 3 separate files so you get the interstitial screen asking which template you'd like to use.

image

**Comment by alanmoo** [comment]
@natalieworth I didn't realize this- it looks like you can create multiple issue templates [using the Github GUI](https://github.com/MozillaFoundation/Design/issues/templates/edit).

Give it a shot [here](https://github.com/MozillaFoundation/Design/issues/templates/edit)

**Comment by mmmavis** [comment]
@alanmoo I _think_ the last step in that GUI flow asks you to either 1) commit the changes (`.md` file) directly to `master` or 2) as a branch. I told Nat it's safer to do it in a branch and create PR so other people get a chance to review it.

**Comment by mmmavis** [comment]
@alanmoo ah, I just realized the file committed in this PR isn't a `.md` file.

@natalieworth how did you create this PR? Did you do it by clicking "create new file"?
image

If so let's close this PR as this just adds a text file to repo. Can you try creating a new PR using the link @alanmoo  mentioned in this comment? https://github.com/MozillaFoundation/Design/pull/360#issuecomment-491857458

**Comment by mmmavis** [comment]
@natalieworth your PR should look similar to https://github.com/mozilla/foundation.mozilla.org/pull/2901/files

**Comment by natalieworth** [comment]
@mmmavis @alanmoo I was able to create the issue template from Alan's link above. In tic #362 

How do I erase/ delete this or cancel? So it doesn't get merged as texted with the other content. :D

**Comment by mmmavis** [comment]
image

**Pull request closed without merging**
